FROM centos:7

WORKDIR /srv
COPY ./install-rpm-deps-centos.sh /srv/
RUN ./install-rpm-deps-centos.sh

# Make sure git is installed
RUN yum install git -y

# Clone the source repos, and run the ci scripts to ensure
# all dependencies are installed.
RUN git clone https://github.com/ostreedev/ostree
RUN git clone https://github.com/projectatomic/rpm-ostree
RUN cd ostree && ci/build.sh && ci/build-check.sh
RUN cd rpm-ostree && ci/build.sh && ci/build-check.sh
RUN rm -rf ostree/ rpm-ostree/
